server:
  port: 9005
  write_timeout: 15
  read_timeout: 15
  idle_timeout: 60
postgres:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  db_name: "postgres"
redis:
  host: "localhost"
  port: 6379
  password: "redis"
logger:
  path: "./logs/logs.log"
  level: 6
secure:
  jwt_key: "someSecureKey"
  password_salt: "someSecureSalt"
